"""Add title column

Revision ID: 18c9e377484b
Revises: 08fe877b04c0
Create Date: 2024-10-09 11:36:47.486741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c9e377484b'
down_revision = '08fe877b04c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_history_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_title'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
