"""Add title column

Revision ID: 22453d3481c3
Revises: 18c9e377484b
Create Date: 2024-10-09 11:39:32.154501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22453d3481c3'
down_revision = '18c9e377484b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
